import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Disclaimer | CurlyHairGuide',
  description: 'Important legal notice regarding our hair diagnostic protocols.',
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-20 px-4">
      <div className="max-w-3xl mx-auto bg-white p-10 rounded-3xl shadow-sm border border-slate-100">
        
        {/* Updated Header */}
        <div className="flex items-center gap-3 mb-6">
          <div className="bg-pink-500 text-white w-10 h-10 flex items-center justify-center rounded-xl font-bold text-xl shadow-md">C</div>
          <h1 className="text-4xl font-serif font-black text-slate-900 leading-tight">Diagnostic Disclaimer</h1>
        </div>
        
        {/* ⚠️ Updated Medical Notice */}
        <div className="bg-amber-50 border-l-4 border-amber-400 p-6 rounded-r-xl mb-10">
            <p className="font-black text-lg text-amber-900 flex items-center gap-2">⚠️ Crucial Medical Notice:</p>
            <p className="font-bold text-amber-800 text-sm mt-1 leading-relaxed">We are not Trichologists, Dermatologists, or Medical Doctors.</p>
        </div>
        
        <div className="prose prose-slate text-slate-700 space-y-6 max-w-none">
          <p>The information provided on <strong className="text-slate-900 font-bold italic">CurlyHairGuide</strong> (the "Site") is for general informational and educational purposes only.</p>
          <p>All diagnostic results, suggested 90-day protocols, weekly calendars, and product recommendations are generated based on user-provided data and are provided in good faith. However, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, or completeness of any information on the Site.</p>
          
          <h3 className="text-xl font-bold text-slate-900 pt-4">Not Clinical Hair Advice</h3>
          <p>The Site cannot and does not contain clinical hair advice or diagnosis. The technical hair-care information is provided for educational and diagnostic purposes only and is not a substitute for professional clinical advice. We strongly recommend consulting with a certified trichologist, dermatologist, or qualified medical professional before making significant changes to your hair-care routine or trying new treatments, especially if you suffer from scalp conditions, severe hair loss, or irritation.</p>
          
          <h3 className="text-xl font-bold text-slate-900 pt-4">Use at Your Own Risk</h3>
          <p>Your use of the Site and your reliance on any diagnostic information or protocols generated by the Site is <strong className="text-slate-900 font-black">solely at your own risk.</strong> CurlyHairGuide assumes no responsibility for adverse reactions, irritation, or lack of results resulting from the application of our generated protocols.</p>
          
          {/* Affiliate Notice */}
          <div className="p-4 bg-slate-100 rounded-xl text-xs text-slate-600 border border-slate-200 mt-10">
            <strong>Affiliate Disclosure:</strong> CurlyHairGuide participates in various affiliate programs. We may receive commissions on purchases made through links on this Site at no additional cost to you. These commissions help support the research and operation of this diagnostic platform.
          </div>
        </div>

        <div className="mt-12 pt-8 border-t border-slate-100">
            <Link href="/" className="text-pink-600 font-bold hover:underline group flex items-center gap-2">
                &larr; <span className="group-hover:-translate-x-1 transition-transform">Back to Diagnostic Quiz</span>
            </Link>
        </div>
      </div>
    </div>
  );
}